server:
  port: 8200
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/duoduo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123zxc
  application:
    name: duoduo-admin-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alibaba:
      seata:
        tx-service-group: duoduo-admin-producer-group
  transaction:
    rollback-on-commit-failure: true
  main:
    allow-bean-definition-overriding: true

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

