server:
  port: 8500
spring:
  application:
    name: bs-ccr-tx-manager

  datasource:
    #type: org.springframework.jdbc.datasource.DelegatingDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/duoduo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123zxc

  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123zxc
    database: 0
tx-lcn:
  manager:
    host: 127.0.0.1
    port: 8070
    heart-time: 300000
    dtx-time: 8000

